name: Deploy project

on:
  push:
    branches:
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.PORTFOLIO_PROJECTS_EC2 }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 43.204.116.131 >> ~/.ssh/known_hosts

      - name: Deploy app to EC2
        run: |
          ssh -i ~/.ssh/id_rsa ec2-user@43.204.116.131 << 'EOF'
            cd ~/applications/WeeURL/wee-url-server
            git pull origin production
            yarn
            pm2 restart all
          EOF
